"""asociation

Revision ID: 742727a4acd2
Revises: b4e4f4ae375a
Create Date: 2021-07-19 12:35:21.651284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '742727a4acd2'
down_revision = 'b4e4f4ae375a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_plans', sa.Column('task_id', postgresql.UUID(), nullable=False))
    op.drop_constraint('task_plans_company_task_id_fkey', 'task_plans', type_='foreignkey')
    op.create_foreign_key(None, 'task_plans', 'company_task', ['task_id'], ['id'])
    op.drop_column('task_plans', 'company_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_plans', sa.Column('company_task_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_plans', type_='foreignkey')
    op.create_foreign_key('task_plans_company_task_id_fkey', 'task_plans', 'company_task', ['company_task_id'], ['id'])
    op.drop_column('task_plans', 'task_id')
    # ### end Alembic commands ###
