"""associations

Revision ID: b4e4f4ae375a
Revises: 5d204ca75e62
Create Date: 2021-07-19 12:28:08.913544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4e4f4ae375a'
down_revision = '5d204ca75e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(), nullable=False),
    sa.Column('company_task_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_task_id'], ['company_task.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id', 'plan_id', 'company_task_id')
    )
    op.create_index(op.f('ix_task_plans_id'), 'task_plans', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_plans_id'), table_name='task_plans')
    op.drop_table('task_plans')
    # ### end Alembic commands ###
