"""company_name

Revision ID: e4dc69bc9afa
Revises: 742727a4acd2
Create Date: 2025-04-05 07:58:46.360611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4dc69bc9afa'
down_revision = '742727a4acd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_name_key', 'company', type_='unique')
    op.alter_column('plan', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('plan', 'tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('tasks', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.alter_column('plan', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('company_name_key', 'company', ['name'])
    # ### end Alembic commands ###
